name: assignment_one
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+2
  google_maps_flutter: ^2.0.10
  geocoding: ^2.0.0
  geolocator: ^10.1.1
  sqflite: ^2.0.0+3
  location_picker_flutter_map: ^3.0.1
  open_street_map_search_and_pick: ^0.1.1
  riverpod: ^2.5.1
  path_provider: ^2.1.3
  provider: ^6.1.2
  flutter_share: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.2.0

flutter:
  uses-material-design: true
